on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/KSXGitHub/test-pacman-repo-builder.repo.git repository

      - name: Generate .SRCINFO files
        uses: ./actions/arch-run
        with:
          command: build-pacman-repo sync-srcinfo --update

      - name: Inspect build directory
        run: ls -A build/*

      - name: Build pacman packages
        uses: ./actions/arch-run
        with:
          command: build-pacman-repo build --syncdeps

      - name: Inspect build directory
        run: ls -A build/*

      - name: Inspect repository
        run: ls -A repository

      - name: Inspect installed binaries
        uses: ./actions/arch-run
        with:
          command: |
            hello-world-c
            hello-world-rust
