on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/KSXGitHub/test-pacman-repo-builder.repo.git repository

      - name: Init AUR Builder
        uses: pacman-repo-builder/action@0.0.0-rc.43
        with:
          command: build-pacman-repo init-aur-builder

      - name: Inspect created manifest
        run: cat build-pacman-repo.yaml

      - name: Inspect build directory
        run: ls -A build/*

      - name: Build pacman packages
        uses: pacman-repo-builder/action@0.0.0-rc.43
        with:
          command: build-pacman-repo build

      - name: Inspect build directory
        run: ls -A build/*

      - name: Inspect repository
        run: ls -A repository

      - name: Inspect installed binaries
        uses: pacman-repo-builder/action@0.0.0-rc.43
        with:
          command: |
            pacman -U repository/*.pkg.tar.zst --noconfirm
            which dialect

      - name: Upload packages
        env:
          GIT_USER_NAME: ${{ secrets.TARGET_REPO_GIT_USER }}
          GIT_USER_EMAIL: ${{ secrets.TARGET_REPO_GIT_EMAIL }}
          GIT_PASSWORD: ${{ secrets.TARGET_REPO_GIT_PASSWORD }}
        run: |
          cd repository
          git config user.name $GIT_USER_NAME
          git config user.email $GIT_USER_EMAIL
          git add -v .
          git commit -m 'Update' --allow-empty
          echo username=KSXGitHub >> /tmp/git-login.txt
          echo password=$GIT_PASSWORD >> /tmp/git-login.txt
          echo '#! /bin/bash' >> /tmp/credential-helper
          echo 'cat /tmp/git-login.txt' >> /tmp/credential-helper
          chmod +x /tmp/credential-helper
          git config credential.helper '/tmp/credential-helper'
          git push origin master
