on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/KSXGitHub/test-pacman-repo-builder.repo.git repository

      - name: Generate .SRCINFO files
        uses: ./actions/arch-run
        with:
          command: build-pacman-repo sync-srcinfo --update

      - name: Inspect build directory
        run: ls -A build/*

      - name: Build pacman packages
        uses: ./actions/arch-run
        with:
          command: build-pacman-repo build --syncdeps

      - name: Inspect build directory
        run: ls -A build/*

      - name: Inspect repository
        run: ls -A repository

      - name: Inspect installed binaries
        uses: ./actions/arch-run
        with:
          command: |
            pacman -U repository/*.pkg.tar.zst --noconfirm
            hello-world-c
            hello-world-rust

      - name: Upload packages
        env:
          GIT_USER_NAME: ${{ secrets.TARGET_REPO_GIT_USER }}
          GIT_USER_EMAIL: ${{ secrets.TARGET_REPO_GIT_EMAIL }}
          GIT_PASSWORD: ${{ secrets.TARGET_REPO_GIT_PASSWORD }}
        run: |
          cd repository
          git config user.name $GIT_USER_NAME
          git config user.email $GIT_USER_EMAIL
          git add -v .
          git commit -m 'Update' --allow-empty
          git push https://KSXGitHub:$GIT_PASSWORD@github.com/KSXGitHub/test-pacman-repo-builder.repo.git master
